### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by min-shui** [battcn/spring-boot-starter-swagger#1]
集成后访问
http://localhost:8080/swagger-ui.html

![image](https://user-images.githubusercontent.com/2221640/34377645-e489cf16-eb2c-11e7-8295-3d5692c12526.png)

JS报错
DApiUI.js:21  Uncaught TypeError: Cannot read property 'location' of undefined

**Comment by levin950825** [comment]
你好，使用的版本是多少，如果方便 加下我QQ 1837307557  我看看问题

**Comment by min-shui** [comment]
搞定了，感谢
